name: Build BModPack

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - name: Create or update Release
        id: release
        uses: actions/create-release@v1
        continue-on-error: true
        with:
          tag_name: main
          release_name: BModPack Release
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    needs: create-release
    runs-on: ubuntu-latest
    name: Build on Linux
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libcurl4-openssl-dev libarchive-dev zlib1g-dev

      - name: Compile
        run: |
          gcc -o modpacker main.c \
            -larchive -lcurl -lssl -lcrypto -lz

      - name: Upload Linux binary to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./modpacker
          asset_name: modpacker-linux
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    needs: create-release
    runs-on: macos-latest
    name: Build on macOS
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install libarchive

      - name: Compile
        run: |
          gcc -o modpacker main.c \
            -I$(brew --prefix openssl)/include \
            -I$(brew --prefix libarchive)/include \
            -L$(brew --prefix openssl)/lib \
            -L$(brew --prefix libarchive)/lib \
            -larchive -lcurl -lssl -lcrypto -lz

      - name: Upload macOS binary to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./modpacker
          asset_name: modpacker-macos
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
